live:
  - name: Arbitrum
    networks:
      - name: Mainnet (Infura)
        chainid: 42161
        id: arbitrum-main
        host: https://arbitrum-mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
        explorer: https://api.arbiscan.io/api
        multicall2: "0x80C7DD17B01855a6D2347444a0FCC36136a314de"
      - name: Testnet
        chainid: 421611
        id: arbitrum-test
        host: https://rinkeby.arbitrum.io/rpc
        explorer: https://rinkeby-explorer.arbitrum.io

      - name: BSC (Moralis)
        chainid: 56
        id: bsc-moralis
        host: https://speedy-nodes-nyc.moralis.io/$MORALIS_PROJECT_ID/bsc/mainnet
        explorer: https://bscscan.com

      - name: BSC-TESTNET-moralis
        id: bsc-test-moralis
        host: https://speedy-nodes-nyc.moralis.io/$MORALIS_PROJECT_ID/bsc/testnet
        chainid: 97
        explorer: https://testnet.bscscan.com

development:
  - name: Ganache-CLI (Arbitrum-Mainnet Fork)
    id: arbitrum-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: arbitrum-main

  - name: Hardhat (Arbitrum Fork)
    id: hardhat-arbitrum-fork
    cmd: npx hardhat node
    host: http://127.0.0.1
    timeout: 240
    cmd_settings:
      port: 8545
      fork: arbitrum-main

  - name: BSC-FORK-Moralis
    id: bsc-main-fork
    cmd: npx hardhat node
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      fork: bsc-moralis
